# Programmation Orientée Objets

In [1]:
import numpy as np
from datetime import date, time, datetime
from zoneinfo import ZoneInfo # dictionnaire IANA python 3.9+ (ex dépendance externe pytz)

## Introduction

In [2]:
# qqs objets
city = "Toulouse"
nb_persons = 6
coords = 4 + 5j 

In [3]:
# city est un objet de la classe str (modèle)
type(city)

str

In [4]:
print(str)
print(complex)
print(int)

<class 'str'>
<class 'complex'>
<class 'int'>


In [5]:
# méthodes
# - 1 fonction qui est attachée à 1 type 
# - appelées sur l'objet en prefixe : objet.method(...)

print(city.upper()) # str method
print(city.startswith('To'))
# print(nb_persons.upper()) # AttributeError: 'int' object has no attribute 'upper'
print(nb_persons.bit_length()) # int method
print(coords.conjugate()) # complex method

TOULOUSE
True
3
(4-5j)


In [6]:
# attributs, propriétés, champs = valeurs

print(coords)
# complex attributes
print(coords.real)
print(coords.imag)

(4+5j)
4.0
5.0


### Tableau Numpy

In [7]:
# focus sur l'exemple des tableaux numpy
data = np.random.normal(10.0, 2.5, 1_000_000)
print(type(data)) # class ndarray (N Dimensional Array)
data

<class 'numpy.ndarray'>


array([10.63005783, 10.63473592,  8.29826812, ..., 15.15591758,
       10.19779876,  6.22976591], shape=(1000000,))

In [8]:
# ndarray methods
print(data.mean())
print(data.std())

# ndarray attributes
print(data.shape)
print(data.dtype)

10.001457509276019
2.498339808883684
(1000000,)
float64


In [9]:
data = data.reshape(1000, 1000)
print(data.shape)

(1000, 1000)


## Données temporelles
- module datetime, ISO 8601
- types : date, time, datetime


In [10]:
# constructeur = fonction qui a le même nom que la classe
d = date(2028, 2, 29)
t = time(9, 45)
dt = datetime(2000, 2, 29, 12, 30, 15, 123456)
print(d)
print(t)
print(dt)

2028-02-29
09:45:00
2000-02-29 12:30:15.123456


In [11]:
for o in d, t, dt:
    print(o, 'has type', type(o))

2028-02-29 has type <class 'datetime.date'>
09:45:00 has type <class 'datetime.time'>
2000-02-29 12:30:15.123456 has type <class 'datetime.datetime'>


In [12]:
# attributes
print(d.year, d.month, d.day)
print(t.hour, t.minute, t.second, t.microsecond, t.tzinfo)
print(dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second, dt.microsecond, dt.tzinfo)

2028 2 29
9 45 0 0 None
2000 2 29 12 30 15 123456 None


In [13]:
# tableau des formats personnalisés de date
# https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior
print(d.strftime('%d/%m/%Y'))
print(d.strftime('%d/%m/%y'))

print(f"date : {d:%d/%m/%Y}")  # calls .strftime(format)
print(f"date heure : {dt:%H:%M:%S %d/%m/%Y}")

29/02/2028
29/02/28
date : 29/02/2028
date heure : 12:30:15 29/02/2000


In [14]:
tz_bra = ZoneInfo("America/Sao_Paulo")

# méthode de classe
d2 = date.today()
dt2 = datetime.now()
dt3 = datetime.now(tz=tz_bra)

texte = "10:15 17/06/2026"
dt4 = datetime.strptime(texte, "%H:%M %d/%m/%Y")

# méthode objet
t2 = dt2.time()

print(d2)
print(dt2)
print(dt3)
print(dt4)
print(t2)

2026-06-17
2026-06-17 11:46:53.077907
2026-06-17 06:46:53.077967-03:00
2026-06-17 10:15:00
11:46:53.077907


In [15]:
dt4.isocalendar()

datetime.IsoCalendarDate(year=2026, week=25, weekday=3)

## Builtin et operators

In [16]:
print(len(city))
print(len(data))
# print(len(dt)) # TypeError: object of type 'datetime.datetime' has no len()

8
1000


In [17]:
for letter in city:
    print(letter, end=' ')
print()

T o u l o u s e 


In [18]:
it = iter(city)
it

In [19]:
it = iter(data)
it

In [20]:
# TypeError: 'datetime.datetime' object is not iterable
# it = iter(dt)
# it

In [21]:
print(dt)  # ISO format
dt         # type + composantes

2000-02-29 12:30:15.123456


datetime.datetime(2000, 2, 29, 12, 30, 15, 123456)

In [22]:
print(data[:3, :3])  # tableau en 2D avec padding
data[:3, :3]         # type + data (+ shape)

[[10.63005783 10.63473592  8.29826812]
 [ 8.64397739  9.51002522  8.55920377]
 [11.0002095  10.4916703   6.97220857]]


array([[10.63005783, 10.63473592,  8.29826812],
       [ 8.64397739,  9.51002522,  8.55920377],
       [11.0002095 , 10.4916703 ,  6.97220857]])

In [23]:
print(f"city = {city}")  # calls str()  => end user
print(city)              # calls str()
city                     # calls repr()  => developer

city = Toulouse
Toulouse


'Toulouse'

In [24]:
# différents
print(str(dt))
print(repr(dt))

# identiques
print(str(nb_persons))
print(repr(nb_persons))

print(str(it)) # default str/repr de tout objet en Python
print(repr(it))


2000-02-29 12:30:15.123456
datetime.datetime(2000, 2, 29, 12, 30, 15, 123456)
6
6


In [25]:
# len()  => __len__()
# iter() => __iter__()
# next() => __next__()
# str()  => __str__()
# repr() => __repr__()
# bool() => __bool__()  # valeur de vérité

print(city.__len__())  # str.__len__ implemente la builtin len()
print(city.__iter__())
print(city.__str__())
print(city.__repr__())

8
Toulouse
'Toulouse'


In [26]:
# idem avec les operateurs
data[:3, :3] + 4    # .__add__

array([[14.63005783, 14.63473592, 12.29826812],
       [12.64397739, 13.51002522, 12.55920377],
       [15.0002095 , 14.4916703 , 10.97220857]])

In [27]:
data[:3, :3].__add__(4)

array([[14.63005783, 14.63473592, 12.29826812],
       [12.64397739, 13.51002522, 12.55920377],
       [15.0002095 , 14.4916703 , 10.97220857]])

In [28]:
4 + data[:3, :3]

array([[14.63005783, 14.63473592, 12.29826812],
       [12.64397739, 13.51002522, 12.55920377],
       [15.0002095 , 14.4916703 , 10.97220857]])

In [29]:
x = 4
echantillon = data[:3, :3]
x.__add__(echantillon)

NotImplemented

In [30]:
echantillon.__radd__(x)

array([[14.63005783, 14.63473592, 12.29826812],
       [12.64397739, 13.51002522, 12.55920377],
       [15.0002095 , 14.4916703 , 10.97220857]])

In [31]:
print(nb_persons.__add__(dt))
print(dt.__radd__(nb_persons))
# nb_persons + dt #  TypeError: unsupported operand type(s) for +: 'int' and 'datetime.datetime'

NotImplemented
NotImplemented


## Movies
classe métier

In [32]:
from movie import Movie


m = Movie("Interstellar", 2014)
print(type(m))
print(m) # str
m # repr

<class 'movie.Movie'>
Interstellar (2014)


Movie(title='Interstellar', year=2014, duration=None)

In [33]:
m2 = Movie("Mon Oncle", 1958, 116) # paramètres par position (positional)
m3 = Movie(title="Dune: Part One", year=2021, duration=155) # paramètres par nom (keyword)
m4 = Movie("Princess Bride", 1987, duration=98)
m5 = Movie("The Mandalorian and Grogu", 2026)

In [35]:
movies = [m, m2, m3, m4, m5]
for movie in movies:
    print(movie) # str
    print(repr(movie))
    print("\t- title:", movie.title)
    print("\t- year:", movie.year)
    print("\t- duration:", movie.duration if movie.duration is not None else 'unknown')

Interstellar (2014)
Movie(title='Interstellar', year=2014, duration=None)
	- title: Interstellar
	- year: 2014
	- duration: unknown
Mon Oncle (1958)
Movie(title='Mon Oncle', year=1958, duration=116)
	- title: Mon Oncle
	- year: 1958
	- duration: 116
Dune: Part One (2021)
Movie(title='Dune: Part One', year=2021, duration=155)
	- title: Dune: Part One
	- year: 2021
	- duration: 155
Princess Bride (1987)
Movie(title='Princess Bride', year=1987, duration=98)
	- title: Princess Bride
	- year: 1987
	- duration: 98
The Mandalorian and Grogu (2026)
Movie(title='The Mandalorian and Grogu', year=2026, duration=None)
	- title: The Mandalorian and Grogu
	- year: 2026
	- duration: unknown


## Geometrie

In [36]:
from geometry import Point

In [37]:
p1 = Point()
p2 = Point(3.5, 4.25)
p3 = Point(x=7.7, y=1.25, name="C")
points = [p1, p2, p3]

In [38]:
for pt in points:
    print(pt)
    print(repr(pt))
    print()

(0.0, 0.0)
Point(x=0.0, y=0.0, name=None)

(3.5, 4.25)
Point(x=3.5, y=4.25, name=None)

C(7.7, 1.25)
Point(x=7.7, y=1.25, name='C')

